---
# tasks file for users_and_groups

- name: configure sudoers file in sudoers.d
  template:
    src: templates/sudoersfile
    dest: /etc/sudoers.d/sudoersfile
    mode: 0440
    validate: 'visudo -cf %s'
  tags: yash


- name: Ensure all the required groups exist on the system
  group:
    name: "{{ item }}"
    state: present
  loop:
    - dev
    - devlead
    - devops
    - devopslead
  tags: yash


- name: Create new users
  user:
    name: "{{ item.split(',')[0] | trim }}"
    groups: "{{ item.split(',')[1] | trim }}"
    shell: /bin/bash
    state: "{{ item.split(',')[2] | trim }}"
    remove: yes
  with_items: "{{ lookup('file', 'add_userlist').split('\n') }}"
  tags: yash


- name: Set up authorized key
  authorized_key:
    user: "{{ item.split(',')[0] | trim }}"
    state: present
    key: "{{ lookup('file', 'pub_keys/{{ item.split(\",\")[0] }}' )}}"
  with_items: "{{ lookup('file', 'add_userlist').split('\n') }}"
  ignore_errors: true
  tags: yash

