
- name: Check if Keypair Exists
  stat:
    path: "{{ key_gen_path }}/{{ org.employees[item.name].name }}"
  register: key
  with_items: 
    - "{{ org.environments[ENV].members }}"
  tags:
    - key_mgmt

- name: Ensure SSH key is generated
  shell: ssh-keygen -t rsa -f "{{ key_gen_path }}"/{{ org.employees[item.name].name }} -C {{ org.employees[item.name].name }} -q -N ""
  args:
    creates: "{{ key_gen_path }}/{{ org.employees[item.name].name }}"
  with_items:
    - "{{ org.environments[ENV].members }}"
  check_mode: no
  tags:
    - key_mgmt
